import { useState, useEffect, useRef } from 'react';
import { HelpCircle, X, Loader2, LifeBuoy } from 'lucide-react';
import { api } from '../api';

// Per-page "how to use this page" help. The "?" lives in the header on every page;
// clicking it opens a drawer with an AI-written guide for the current page
// (generated by Claude on first view, then cached server-side). Managers can
// regenerate it. Neil: every page has help, AI keeps it current, no human authoring.

// Cache fetched help across opens within a session so reopening is instant.
const _cache = new Map();

// Tiny Markdown → React renderer (headings, bullets, bold, paragraphs) — enough
// for the short guides the help endpoint returns; no external dependency.
function renderInline(text, keyBase) {
  const parts = String(text).split(/(\*\*[^*]+\*\*)/g).filter(Boolean);
  return parts.map((p, i) =>
    p.startsWith('**') && p.endsWith('**')
      ? <strong key={`${keyBase}-${i}`}>{p.slice(2, -2)}</strong>
      : <span key={`${keyBase}-${i}`}>{p}</span>
  );
}
function renderMarkdown(md) {
  const lines = String(md || '').replace(/```/g, '').split('\n');
  const out = [];
  let bullets = null;
  const flush = () => { if (bullets) { out.push(<ul key={`ul-${out.length}`} style={{ margin: '4px 0 12px', paddingLeft: 20, display: 'flex', flexDirection: 'column', gap: 6 }}>{bullets}</ul>); bullets = null; } };
  lines.forEach((raw, i) => {
    const line = raw.trim();
    if (!line) { flush(); return; }
    if (line.startsWith('### ')) { flush(); out.push(<h4 key={i} style={{ margin: '14px 0 6px', fontSize: 13, fontWeight: 800, letterSpacing: '.02em', color: 'var(--ink)' }}>{renderInline(line.slice(4), i)}</h4>); return; }
    if (line.startsWith('## '))  { flush(); out.push(<h3 key={i} style={{ margin: '14px 0 6px', fontSize: 15, fontWeight: 800, color: 'var(--ink)' }}>{renderInline(line.slice(3), i)}</h3>); return; }
    if (line.startsWith('# '))   { flush(); out.push(<h3 key={i} style={{ margin: '14px 0 6px', fontSize: 15, fontWeight: 800, color: 'var(--ink)' }}>{renderInline(line.slice(2), i)}</h3>); return; }
    if (/^[-*]\s+/.test(line))   { (bullets ||= []).push(<li key={i} style={{ fontSize: 13, lineHeight: 1.55, color: 'var(--ink)' }}>{renderInline(line.replace(/^[-*]\s+/, ''), i)}</li>); return; }
    flush();
    out.push(<p key={i} style={{ margin: '0 0 10px', fontSize: 13, lineHeight: 1.6, color: 'var(--ink)' }}>{renderInline(line, i)}</p>);
  });
  flush();
  return out;
}

export default function PageHelp({ pageKey, label }) {
  const [open, setOpen] = useState(false);
  const [data, setData] = useState(null);   // { content, title, source, updated_at }
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');
  const lastKey = useRef(null);

  useEffect(() => {
    if (!open) return;
    if (_cache.has(pageKey)) { setData(_cache.get(pageKey)); return; }
    if (lastKey.current === pageKey && data) return;
    lastKey.current = pageKey;
    setLoading(true); setError('');
    api.getPageHelp(pageKey, label)
      .then(d => { _cache.set(pageKey, d); setData(d); })
      .catch(() => setError('Could not load help for this page.'))
      .finally(() => setLoading(false));
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [open, pageKey]);

  // Esc closes the drawer.
  useEffect(() => {
    if (!open) return;
    const h = e => e.key === 'Escape' && setOpen(false);
    window.addEventListener('keydown', h);
    return () => window.removeEventListener('keydown', h);
  }, [open]);

  function goToAccessHelp() {
    setOpen(false);
    window.dispatchEvent(new CustomEvent('nexus:navigate', { detail: { view: 'support' } }));
  }

  return (
    <>
      <button className="icon-btn help-pill" onClick={() => setOpen(true)} aria-label="Help for this page" title="How to use this page">
        <HelpCircle style={{ width: 16, height: 16, flexShrink: 0 }} />
        <span className="help-pill-label">Help</span>
      </button>
      {open && (
        <div onClick={e => e.target === e.currentTarget && setOpen(false)}
          style={{ position: 'fixed', inset: 0, background: 'rgba(0,0,0,0.4)', zIndex: 1300, display: 'flex', justifyContent: 'flex-end' }}>
          <div style={{ width: 'min(420px, 96vw)', height: '100%', background: 'var(--card)', boxShadow: '-12px 0 40px rgba(0,0,0,0.22)', display: 'flex', flexDirection: 'column', animation: 'helpSlideIn .22s ease' }}>
            <style>{`@keyframes helpSlideIn{from{transform:translateX(20px);opacity:.4}to{transform:none;opacity:1}}`}</style>
            <div style={{ padding: '16px 20px 14px', borderBottom: '1px solid var(--line)', display: 'flex', alignItems: 'center', gap: 10, flexShrink: 0 }}>
              <HelpCircle size={18} style={{ color: 'hsl(var(--color-blue))', flexShrink: 0 }} />
              <div style={{ flex: 1, minWidth: 0 }}>
                <div style={{ fontSize: 14.5, fontWeight: 800, color: 'var(--ink)', overflow: 'hidden', textOverflow: 'ellipsis', whiteSpace: 'nowrap' }}>{data?.title || label || 'Help'}</div>
                <div style={{ fontSize: 11, color: 'var(--muted)' }}>How to use this page</div>
              </div>
              <button className="icon-btn" onClick={() => setOpen(false)} aria-label="Close"><X style={{ width: 17, height: 17 }} /></button>
            </div>
            <div style={{ flex: 1, overflowY: 'auto', padding: '16px 20px' }}>
              {loading ? (
                <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 10, padding: '40px 0', color: 'var(--muted)', fontSize: 13 }}>
                  <Loader2 size={22} style={{ animation: 'spin 1s linear infinite' }} />
                  Writing this page’s guide…
                </div>
              ) : error ? (
                <div style={{ color: 'hsl(var(--color-red))', fontSize: 13 }}>{error}</div>
              ) : data ? (
                renderMarkdown(data.content)
              ) : null}
            </div>
            <div style={{ padding: '11px 16px', borderTop: '1px solid var(--line)', flexShrink: 0 }}>
              <button onClick={goToAccessHelp}
                style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 7, width: '100%', padding: '9px 12px', borderRadius: 9, border: '1px solid var(--line)', background: 'var(--card)', cursor: 'pointer', fontSize: 12.5, fontWeight: 700, color: 'hsl(var(--color-blue))', fontFamily: 'Inter,sans-serif' }}>
                <LifeBuoy size={14} /> Help with access &amp; all of Nexus →
              </button>
            </div>
          </div>
        </div>
      )}
    </>
  );
}
